version: 2
updates:
  ##############################
  #         Root Package       #
  ##############################
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "nestia"
      - dependency-name: "@nestia/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "@prisma/*"
      - dependency-name: "prisma"
      - dependency-name: "prisma-markdown"
      - dependency-name: "prisma-markdown"
      - dependency-name: "typia"
      - dependency-name: "typescript"
      - dependency-name: "typescript-transform-paths"
      - dependency-name: "ts-patch"
      - dependency-name: "rxjs"
      - dependency-name: "rxjs-operators"
    groups:
      Samchon:
        patterns:
          - "@nestia/*"
          - "nestia"
          - "typia"
          - "prisma-markdown"
      NestJS:
        patterns:
          - "@nestjs/*"
      Prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      TypeScript:
        patterns:
          - "typescript"
          - "typescript-transform-paths"
          - "ts-patch"
      RxJS:
        patterns:
          - "rxjs"
          - "rxjs-operators"
  ##############################
  #         API Package        #
  ##############################
  - package-ecosystem: "npm"
    directory: '/packages/api'
    schedule:
      interval: "daily"
    open-pull-requests-limit: 25
    versioning-strategy: increase
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"
    groups:
      Samchon:
        patterns:
          - "@nestia/fetcher"
          - "typia"
